default: &default
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  advisory_locks: false
<% if ENV.include?('DATABASE_URL') %>
  url: <%= ENV.fetch('DATABASE_URL') %>
<% end %>
  pool: <%= (ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 40) * 1.2 %>
  connect_timeout: 5
  checkout_timeout: 2
  reaping_frequency: 30
  variables:
    lock_timeout: 6s
    statement_timeout: 15s

development:
  <<: *default
  database: dummy_graphql_fancy_loader

test:
  <<: *default
  database: dummy_graphql_fancy_loader_test
