name: Release FancyLoader gem

on:
  push:
    branches:
      - main
    paths:
      - "lib/graphql/fancy_loader/version.rb"

jobs:
  release:
    name: Relase to Rubygems
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Authenticate with Rubygems
        run: |
          echo "${RUBYGEMS_CREDENTIALS}" > $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
        env:
          RUBYGEMS_CREDENTIALS: ${{ secrets.SENKO_SAN_RUBYGEMS_CREDENTIALS }}

      - name: Publish Gem on Rubygems
        run: bundle exec rake release

      - name: Create a Github Release
        run: gh release create $(ruby -r './lib/graphql/fancy_loader/version' -e "puts GraphQL::FancyLoader::VERSION") --target releasing
        env:
          GITHUB_TOKEN: ${{ secrets.SENKO_SAN_KEY }}
